name: Workflow
on: 
    push:
        branches: 
            - ANALISIS-LAB
jobs: 
    SAST:
        runs-on: ubuntu-latest
        steps: 
            # - name: Hola mundo
            #   run: |
            #     echo "pruab de análisis"
            - name: Set up JDK 17
              uses: actions/setup-vava@v2
              with:
                java-version: 17
                distribution: 'adopt'
                        
            - name: Checkout code
              uses: actions/checkout@v2
            
            - name: build
              run: |
                chmod 777 gradlew
                ./gradlew build  
            - name: Validando proyecto con Sonar
              run: |
                curl -f -X POST -u '${{secrets.SONAR_TOKEN}}:' 'https://sonarcloud.io/api/projects/create' -d 'name=${{github.event.repository.name}}' -d 'project=${{github.event.repository.name}}' -d 'organization=franciscopainemal' -d 'visibility=public'
                if[ $? -ne 0]; then
                    echo "el proyecto ya existe en SonarCloud"
                else
                    echo ""Proyecto creado exitosamente con SonarCloud"
                fi
