name: Workflow
on: 
    push:
        branches: 
            - ANALISIS-LAB
jobs: 
    SAST:
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout code
              uses: actions/checkout@v2
            
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 18

            - name: Instalando dependencias
              run: npm ci

            - name: Build React
              run: npm run build
                
            - name: Validando existencia del proyecto en SonarQube
              run: |
                set +e
                curl -f -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/projects/create' -d 'name=${{github.event.repository.name}}' -d 'project=${{github.event.repository.name}}' -d 'organization=franciscopainemal' -d 'visibility=public'
                if [ $? -ne 0 ]; then
                    echo "el proyecto ya existe en SonarCloud"
                    echo ":: set-output name=proyectoExiste::1"
                else
                    echo "Proyecto ${{github.event.repository.name}} creado exitosamente con SonarCloud"
                    echo "Se establece rama Main como rama por defecto"
                    curl -f -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/project_branches/rename' -d 'name=main' -d 'project=${{ github.event.repository.name }}'                
                fi
                set -e

            -  name: Validando el tipo de proyecto
               run: | 
                if [ -f "package.json" ]; 
                then    
                    if grep -q '"react"' package.json 
                    then
                        echo "Proyecto es React."
                    else   
                        echo "El proyecto no es del tipp React."
                        exit 1
                    fi
                else 
                    echo "No se encontró archivo."
                    exit 1
                fi
            - name: Ejecutando SonarCloud
              run: |
                npx sonar-scanner \
                  -Dsonar.projectKey=${{ github.event.repository.name }} \
                  -Dsonar.organization=franciscopainemal \
                  -Dsonar.host.url=https://sonarcloud.io \
                  -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
                  -Dsonar.branch.name=main

            # - name: Ejecutando SonarCloud
            #   uses: SonarSource/sonarcloud-github-action@v2
            #   with:
            #     projectBaseDir: .
            #   env:
            #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            #     SONAR_PROJECT_KEY: franciscopainemal_${{ github.event.repository.name }}
            #     SONAR_ORGANIZATION: franciscopainemal
            - name: Validando resultados de SonarQube
              run: |

                # curl -s -X GET -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/ce/component?component=${{ github.event.repository.name }}')
                # idanalisis=$(curl -s -X GET -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/ce/component?component=${{ github.event.repository.name }}')
                # idanalisisParse=$(echo "$idanalisis" | jq .current.analysisId | sed -e 's/^"//' -e 's/"$//')
                # echo "Id del análisis sonarwqube $idanalisisParse"
                # qualitygate=$(curl -s -X GET -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/qualitygates/project_status?analysisId=$idanalisisParse')
                # qualitygatesStatus=$(echo "$qualitygate" | jq .projectStatus.status | sed -e 's/^"//' -e 's/"$//')
                # case $qualitygateStatus in
                #   *"OK"*)
                #     echo "Calidad del código OK"
                #   ;;
                #   *"ERROR"*)
                #     echo "Calidad del código ERROR"
                #     exit 1
                #     ;;
                #   *"WARN"*)
                #     echo "Calidad del código WARN"
                #     exit 1
                #     ;;
                #   *"NONE"*)
                #     echo "Estado NONE de la calidad del codigo $qualitygateStatus"
                #     exit 1
                #     ;;
                # esac
                
                issuesvalidate=$(curl -s -X GET -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarclud.io/api/issues/search?branch=main&componentKeys=${{ github.event.repository.name }}&facets=severities' | jq '.facets[0].values[1].Count')
                if [ "$issuesvalidate" -gt 0 ];
                then
                  echo "Existen dificultades en el código, abortar Pipeline"
                  exit 1
                else
                  echo "Continua Pipeline, código correcto"
                fi

                
    SCA:
      needs: SAST
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalando dependencias
        run: npm ci

      - name: Build React
        run: npm run build
      
      - name: Dependency Check
        uses: dependency-check/Dependency-Check_Action@1.1.0
        env:
          REACT_HOME: /foo
        with:
          project: '${{ github.event.repository.name }}'
          path: '.'
          format: 'HTML'
          out: 'reports'
          args: > 
            --failOnCVSS 7
            --enableRetired
      
      - name: Generar reporte Dependency Check
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-reports
          path: ${{ github.workspace }}/reports

          


 
